<?php
namespace App\Helpers;

class ServerUrl {

    const BASE_URL = "https://api-wls.infinitilotto.com/";
    const TEST_BASE_URL = "https:/api-wls.infinitilotto.com/";
    const CASHIER_BASE_URL = "https://cashier-backend-wls.infinitilotto.com/";
    const CASHIER_SUBMIT_URL = "https://api-wls.infinitilotto.com/";
    const SERVER_PATH = "Weaver/service/rest/";
    const RAM_BASE = "https://ram-backend-wls.infinitilotto.com/";
    const CASHIER_SERVER_PATH = 'player/payment/';
    const IMAGE_UPLOAD = "https://content1.khelplayrummy.com/WeaverDoc/commonContent/imageupload";
    const PLAYER_LOGIN = self::SERVER_PATH . "playerLogin";
    const PLAYER_LOGOUT = self::SERVER_PATH . "playerLogout";
    const CHECK_LOGIN = self::SERVER_PATH . "checkLogin";
    const RAM_SERVER_PATH = "";
    // Ram's Url
    const RAM_PRELOGIN_SEND_OTP = self::RAM_SERVER_PATH . "preLogin/sendRegOtp";
    const RAM_REGISTRATION = self::RAM_SERVER_PATH . "preLogin/registerPlayerWithOtp";
    const RAM_LOGIN = self::RAM_SERVER_PATH . "preLogin/playerLogin";
    const RAM_PLAYER_PROFILE = self::RAM_SERVER_PATH . "postLogin/playerProfile";
    const RAM_UDATE_PLAYER_PROFILE = self::RAM_SERVER_PATH . "postLogin/overallUpdatePlayerProfile";
    const RAM_SEND_EMAIL_VERICATION_CODE = self::RAM_SERVER_PATH . "postLogin/sendVerficationEmailLink";
    const RAM_SEND_MOBILE_VERICATION_CODE = self::RAM_SERVER_PATH . "postLogin/sendOtp";
    const RAM_VERIFY_EMAIL_OTP = self::RAM_SERVER_PATH . "postLogin/verifyEmailWithOtp";
    // const RAM_VERIFY_MOBILE_OTP = self::RAM_SERVER_PATH . "postLogin/verifyMobileWithOtp";
    const GET_COUNTRY_LIST = "preLogin/getCountryList";
    const CAP_GAME_LIST = "https://cap-wls.infinitilotto.com/operatorGateway/api/v1/games?providerId=2";
    const SAVE_SITE_OFFLINE = self::SERVER_PATH . "site/maintain";
    const PLAYER_REGISTRATION = self::SERVER_PATH . "playerRegistration";
    const PLAYER_REGISTRATION_NEW = self::SERVER_PATH . "v1/playerRegistration";
    const PLAYER_PARTIAL_REGISTRATION = self::SERVER_PATH . "partialRegistration";
    const FORGOT_PASSWORD = self::SERVER_PATH . "forgotPassword";
    const CHECK_AVAILABILITY = self::SERVER_PATH . "checkAvailability";
    const PLAYER_PROFILE = self::SERVER_PATH . "playerProfile";
    const EDIT_AVATAR = self::SERVER_PATH . "editAvatar";
    const UPDATE_PLAYER_PROFILE = self::SERVER_PATH . "updatePlayerProfile";
    const PLAYER_INBOX = self::SERVER_PATH . "playerInbox";
    const CHANGE_PASSWORD = self::SERVER_PATH . "changePassword";
    const GET_BALANCE = self::SERVER_PATH . "getBalance";
    const SEND_VERIFICATION_CODE = self::SERVER_PATH . "sendVerificationCode";
    const VERIFY_PLAYER = self::SERVER_PATH . "verifyPlayer";
    const INBOX_ACTIVITY = self::SERVER_PATH . "inboxActivity";
    const UPLOAD_AVATAR = self::SERVER_PATH . "uploadAvatar";
    const UPLOAD_PLAYER_DOCUMENT = self::SERVER_PATH . "uploadPlayerDocument";
    const UPLOAD_PLAYER_DOCUMENT_NEW = self::SERVER_PATH . "uploadPlrDocument";
    const FETCH_DEPOSIT_BONUS = self::SERVER_PATH . "fetchDepositBonus";
    const BONUS_DETAILS = self::SERVER_PATH . "bonusDetails";
    const TRANSACTION_DETAILS = self::SERVER_PATH . "transactionDetails";
    const TRANSACTION_TICKET_DETAILS = self::SERVER_PATH . "ticketDetails";
    const WITHDRAWAL_DETAILS = self::SERVER_PATH . "withdrawalDetails";
    const TICKET_DETAILS = self::SERVER_PATH . "ticketDetails";
    const GET_COMMON_DATA = self::SERVER_PATH . "getCommonData";
    const INVITE_FRIEND = self::SERVER_PATH . "inviteFriend";
    const PAYMENT_OPTIONS = self::CASHIER_SERVER_PATH . "options";
    const OFFLINE_DEPOSIT_REQUEST = self::SERVER_PATH . "offlineDepositRequest";
    const ONLINE_DEPOSIT_REQUEST = "Weaver/portal/cashier/depositRequest";
    const WITHDRAWAL_REQUEST = self::SERVER_PATH . "withdrawalRequest";
    const withdrawal_Poc = self::CASHIER_SERVER_PATH . "withdrawalRequest";
    const SEND_OTP = self::SERVER_PATH . "sendOTP";
    const CANCEL_WITHDRAWAL = self::SERVER_PATH . "cancelWithdrawal";
    const WINNERS_LIST = self::SERVER_PATH . "winnersList";
    const PROMO_CODE_LIST = self::SERVER_PATH . "promoCodeList";
    const VALIDATE_PROMO_CODE = self::SERVER_PATH . "validatePromoCode";
    const PREPARE_CAMPAIGN_TREKKING = self::SERVER_PATH . "prepareCampaignTracking";
    const EMAIL_VERIFY = self::SERVER_PATH . "accountActivationLink";
    const ONLINE_DETAIL = self::SERVER_PATH . "onlineDetail";
    const RESET_PASSWORD_LINK = self::SERVER_PATH . "resetPasswordLink";
    const RESET_PASSWORD = self::SERVER_PATH . "resetPassword";
    const POST_LOGIN_DATA = self::SERVER_PATH . "getPostLoginData";
    const FETCH_CITY_LIST = self::SERVER_PATH . "fetchCityList";
    const FETCH_HEADER_INFO = self::SERVER_PATH . "fetchHeaderInfo";
    const ENCODE_DECODE_API = self::SERVER_PATH . "encodeDecodeApi";
    const LOYAL_PLAYER_DETAIL = self::SERVER_PATH . "loyalPlayerDetail";
    const LOYALTY_REDEEM_PAGE = self::SERVER_PATH . "redeemPage";
    const LOYALTY_GET_CASH = self::SERVER_PATH . "getCash";
    const LOYALTY_BUY_MERCHANDISE = self::SERVER_PATH . "buyMerchandise";
    const LOYALTY_PACKET_STATEMENT = self::SERVER_PATH . "packetStatement";
    const REFER_A_FRIEND = self::SERVER_PATH . "inviteFriend";
    const REFER_A_FRIEND_TRACK_BONUS = self::SERVER_PATH . "plrTrackReferBonus";
    const REFER_A_FRIEND_REMINDER = self::SERVER_PATH . "notificationToPlayer";
    const IS_DEPOSIT_PROCESSABLE = self::SERVER_PATH . "isDepositProcess";
    const SEND_APP_LINK = self::SERVER_PATH . "sendAppLink";
    const REGISTRATION_OTP = self::SERVER_PATH . "registrationOTP";
    const IGEWEB = Configuration::DOMAIN . "/html5/index.php/";    
    const FETCH_GAME_DATA = "/services/tpDataMgmt/fetchGameData";
    const PURCHASE_TICKET = "/services/tpPlayMgmt/purchaseTicket";
    const IGE_GET_GAME_LIST = "getGameList.action";
    const IGE_GAMEPLAY = "loadPortalGame.action";
    const SLOT_GAMEPLAY = "loadGame.action";
    const IGE_GAMEPLAY_MOBILE_BUY = "Gameplay/playforcash";
    const IGE_GAMEPLAY_MOBILE_TRY = "Gameplay/playforfree";
    const IGE_UNFINISHED_GAME_LIST = "unFinishedGameList.action";
    const IGE_GAMEPLAY_UNFINISHED_MOBILE = "Gameplay/playforunfinished";
    const IGE_GAMEPLAY_UNFINISHED = "loadUnfinishGame.action";
    const FETCH_SLE_DRAW_DATA = "/rest/dataMgmt/fetchSLEDrawData";
    const SLE_PURCHASE_TICKET = "/rest/playMgmt/purchaseTicket";
    const FETCH_SLE_MATCHLIST = "/rest/dataMgmt/fetchSLEMatchListData";
    const SLOT_GET_GAME_LIST = "/getGameListData.action";
    const FETCH_SBE_GAME_DATA = "/dataManagement/web/fetchSportsAndTournamentData";
    const FETCH_SBE_MATCH_BET_MARKETS_DATA = "/dataManagement/web/fetchEventDetails";
    const SBE_PURCHASE_TICKET = "/betManagement/web/betSale";
    const IGE_PATH = array(
        "IGEASIA" => Configuration::DOMAIN . "/InstantWinGames/index.php",
        "IGEICE" => Configuration::DOMAIN . "/InstantWinGamesIGEIce/index.php",
        "IGEBETA" => Configuration::DOMAIN . "/InstantWinGamesIGEBeta/index.php",
        "IGE_FLASH" => "https://ige-wls.infinitilotto.com/InstantGameEngine/gamePlay/api/loadPortalGame.action",
	"IGEMS" => Configuration::DOMAIN . "/IWG_Single_Asset/index.php"
    );
    const CONTACT_US =  self::SERVER_PATH ."contactUs";
    const BONUS_BASE = "https://bonus-backend-wls.infinitilotto.com/";
    const BONUS_DETAILS_NEW = "player/checkBonusStatusPlayer";
    const MINI_REGISTRATION = self::RAM_SERVER_PATH . "preLogin/registerPlayerWithOtp";
    const QR_LOGIN = self::RAM_SERVER_PATH . "preLogin/playerLoginByQRCode";
    const RAM_CHANGE_PASSWORD = self::RAM_SERVER_PATH . "postLogin/changePassword";
    const PAM_CONFIG = "https://pam-backend-wls.infinitilotto.com/getConfigValues";
    const FETCH_PENDING_WITHDRAWAL = "player/fetchPendingScanNPlayWithdrawal";
    const WITHDRAWAL_OTP_RESEND = "player/payment/resendWithdrawalOtp";
    const ART_GAME_BASEURL = "https://hg4dev.gahypergaming.com/rgs/api/admin.js";
}
